"""
Django settings for url_shortener project.

Generated by 'django-admin startproject' using Django 3.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '$&m5@&lu8vtmber^4$h@!cnf$u0hs2s_!rs8limf74sbd6)hxl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'url',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
j bvmango.middleware.common.CommonMiddleware',
j bvmango.middleware.csrf.CsrfViewMiddleware',
j bvmango.contrib.auth.middleware.AuthenticationMiddleware',
j bvmango.contrib.messages.middleware.MessageMiddleware',
j bvmango.middleware.clickjacking.XFrameOptionsMiddleware',
j bvm
j bvm
j bvmLCONF = 'url_shortener.urls'
j bvm
j bvmES = [
j bvm
j bvm 'BACKEND': 'django.template.backends.django.DjangoTemplates',
j bvm 'DIRS': [],
j bvm 'APP_DIRS': True,
j bvm 'OPTIONS': {
j bvm     'context_processors': [
j bvm         'django.template.context_processors.debug',
j bvm         'django.template.context_processors.request',
j bvm         'django.contrib.auth.context_processors.auth',
j bvm         'django.contrib.messages.context_processors.messages',
j bvm     ],
j bvm },
j bvm
j bvm
j bvm
j bvmPLICATION = 'url_shortener.wsgi.application'
j bvm
j bvm
j bvmase
j bvm://docs.djangoproject.com/en/3.1/ref/settings/#databases
j bvm
j bvmES = {
j bvmfault': {
j bvm 'ENGINE': 'django.db.backends.sqlite3',
j bvm 'NAME': BASE_DIR / 'db.sqlite3',
j bvm
j bvm
j bvm
j bvm
j bvmord validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
